version: "3.7"
## 暂时未使用
services:
  store-common:
    image: registryxxxx:latest
    ports:
      - "1131:1130"
    networks:
      - common-ingress
    deploy:
      mode: replicated
      replicas: 2
    environment:
      DRAGON: debug #配置环境变量

networks:
  common-ingress:
    driver: overlay
